database_1:
  schema:
    url: jdbc:mysql://localhost:3306/testdb

database_2:
  schema:
    url: jdbc:postgresql://localhost:5432/testdb?currentSchema=data_base_2

data-sources:
  sources:
    - name: data-base-1
      strategy: mysql #this property is optional, only if you implements multiple database type support (Postgres, ORACLE, MySQL...)
      url: ${database_1.schema.url}
      table: users
      user: testuser
      password: testpass
      mapping:
        id: user_id
        username: login
        name: first_name
        surname: last_name
    - name: data-base-2
      strategy: mysql
      url: ${database_2.schema.url}
      table: user_table
      user: testuser
      password: testpass
      mapping:
        id: ldap_login
        username: ldap_login
        name: name
        surname: surname
